#!/bin/bash
# Set wallpaper on all monitors (hyprpaper >= 0.8 syntax)

IMG="$1"
CONF=~/.config/hypr/hyprpaper.conf
MONITORS=$(hyprctl monitors -j | jq -r '.[].name')

# Persist it for next login
{
    echo "# Autogenerated by Quickshell wallpaper picker"
    for MON in $MONITORS; do
        printf 'wallpaper {\n    monitor = %s\n    path = %s\n    fit_mode = cover\n}\n\n' "$MON" "$IMG"
    done
    echo "splash = false"
} > "$CONF"

# Start hyprpaper if it isn't running (it will read the new config)
if ! pgrep -x hyprpaper >/dev/null; then
    setsid hyprpaper >/dev/null 2>&1 &
    sleep 0.5
fi

# Apply immediately over IPC, no restart needed
for MON in $MONITORS; do
    hyprctl hyprpaper wallpaper "$MON, $IMG, cover"
done
